adaption for working with Solaris.
fsbruva/slimserver-vendor pull request #8
Opened 2018-12-25 12:43 UTC by chincheta0815

Okay: Happy Holidays.
I found some small issues before it worked on SunOS.
-> "FLAGS" removed in favor of "*_COMMON" flags,
-> added "-m64" to SunOS ICUFFLAGS,
-> added "*" to some checks for ARCH, e.g. libjpeg...

2018-12-25 14:18 UTC, fsbruva commented
@chincheta0815 
Happy holidays. It looks like a clean merge, and I'm sure the Travis test will pass. I made some comments. Nothing critical... just ideas.

2018-12-26 16:26 UTC, chincheta0815 commented
Okay.
Where are the comments, I did not find them, did you forget them.
I just found an issue concerning 64bit and 32bit wich correspond to *-64 and *-64int arches.
Some distros have the one, others the other on Illumos/Solaris. I therefore added some lines of code making the script cleaner. I think.
I am testing and will push as soon as possible.

2018-12-26 16:35 UTC, fsbruva requested changes

2018-12-26 16:35 UTC, fsbruva commented on CPAN/buildme.sh
> +if [ "$OS" = "SunOS" ]; then
Why not put this inside the SunOS case? It should be like the MAKE_BIN. Set to default before the case, then export after.

2018-12-26 16:35 UTC, fsbruva commented on CPAN/buildme.sh
> +    elif [[ "$ARCH" =~ "i386-linux" || "$ARCH" =~ "x86_64-linux" || "$ARCH" =~ "i86pc-solaris*" || "$OS" = "FreeBSD" ]]; then
You had to add the `*`? The `=~` is supposed to be a regular expression that grabs anything with the stated prefix.

2018-12-26 16:35 UTC, fsbruva commented on CPAN/buildme.sh
> +    elif [[ "$ARCH" =~ "i386-linux" || "$ARCH" =~ "x86_64-linux" || "$ARCH" =~ "i86pc-solaris*" || "$OS" = "FreeBSD" ]]; then
I see my error now, and why the * was necessary. It seems bash in Linux is more accommodating than on Solaris (different build options?). When the rhs of the regex is quoted, it becomes a literal string compare. 
Should make it an exact match, like `^(i86pc-solaris|freebsd|i386-linux|x86_64-linux)`

2018-12-26 16:35 UTC, fsbruva commented
Sorry. I forgot to submit the code review.

2018-12-26 18:08 UTC, fsbruva commented
Yes, the -64int (and -thread and -multi) options need to be accommodated. That's why I had the regex to match the first part, regardless off the compile options for Perl.

2018-12-26 18:53 UTC, fsbruva commented on CPAN/buildme.sh
> +    elif [[ "$ARCH" =~ "i386-linux" || "$ARCH" =~ "x86_64-linux" || "$ARCH" =~ "i86pc-solaris*" || "$OS" = "FreeBSD" ]]; then
`^(i386-linux|x86_64-linux|i86pc-solaris)(-thread|-multi|-64int)*$` is better, then keep the OS check for freebsd (all arches).

2018-12-27 18:26 UTC, fsbruva commented on CPAN/buildme.sh
> +    elif [[ "$ARCH" =~ "i386-linux" || "$ARCH" =~ "x86_64-linux" || "$ARCH" =~ "i86pc-solaris*" || "$OS" = "FreeBSD" ]]; then
I will just merge this in and then make my changes.

2018-12-27 18:27 UTC, fsbruva approved these changes

2018-12-27 18:27 UTC, merged

2018-12-27 18:57 UTC, chincheta0815 commented
Okay. Thanks.
I am checking some things right now.
It would be great if you could include them, before sending them to Michael.